### ISSUE TITLE
How exactly do I compile this?

### ISSUE THREAD

**Issue by gbiagomba** [jrozner/sonar#1]
I installed Go and I looked at the guid I tried doing the following:

go -o Sonar -i -v *.go

And I got this returned

flag provided but not defined: -o
Go is a tool for managing Go source code.

I tried looking for videos on how to install Go applications and I still couldn't get it working

**Comment by jrozner** [comment]
I've added compilation instructions to the README that is displayed in the repository and there are pre-built executables if you'd like to use those in the "Releases"  tab on GitHub. If the instructions for compilation are not clear please ask and I can update them.
